apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: api-app
    app.kubernetes.io/instance: api-app
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: demo-app
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: api-app
    app.kubernetes.io/instance: api-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081