apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels:
    app.kubernetes.io/name: api-app
    app.kubernetes.io/instance: api-app
    app.kubernetes.io/version: "1.14.2"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: demo-app
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-app
      app.kubernetes.io/instance: api-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-app
        app.kubernetes.io/instance: api-app
        app.kubernetes.io/version: "1.14.2"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: demo-app
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
        - name: api-app
          image: image
          imagePullPolicy: IfNotPresent
          command: ["/app/api"]
          env:
            - name: PORT
              value: "8081"
            - name: BOOKS_API_HOST
              value: "books-service.demo-app:8081"
            - name: MOVIES_API_HOST
              value: "movies-service.demo-app:8081"
          ports:
            - name: http
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 1
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
